### ISSUE TITLE
no updates in a while

### ISSUE THREAD

**Issue by angrhub** [d12frosted/elpa-mirror#10]
Hi, I was wondering if the mirror is still maintained. I am using it almost on a weekly basis at work and have seen that some days have passed since the last update.

**Comment by d12frosted** [comment]
Thanks for letting me know. Seems like GitHub disabled the job. I enabled it back. Should be good now.

Cheers,
***@***.***

**Comment by angrhub** [comment]
Thanks for helping me out! (... about two years ago, this repo saved my day after a major change in proxy configs at work)
Cheers

**Comment by d12frosted** [comment]
:heart: really glad that someone uses it! Cheers @angrhub
