### ISSUE TITLE
Is it missing NonGnu Elpa?

### ISSUE THREAD

**Issue by didibus** [d12frosted/elpa-mirror#11]
I think it is missing: https://elpa.nongnu.org/nongnu/

**Comment by d12frosted** [comment]
Thanks for reporting @didibus !

While I am waiting for CI, let me laugh (haha), as I didn't know that it's possible to close issues from other repositories.

**Comment by d12frosted** [comment]
Yup, it's here : https://github.com/d12frosted/elpa-mirror/tree/master/nongnu

Enjoy :)
