### ISSUE TITLE
Cannot open load file: evil-collection-forge 

### ISSUE THREAD

**Issue by jaysharm** [d12frosted/elpa-mirror#12]
I have exactly this issue in spacemacs and am using this github mirror as I'm behind a stringent workplace firewall.
https://github.com/syl20bnr/spacemacs/issues/15179

Do you know how I can update evil-collection?

**Comment by d12frosted** [comment]
Hey,

Spacemacs should have an option to upgrade packages. So just use that functionality. Or remove `evil-collection` from your cache. 

This mirror is being updated every 4 hours. And `evil-collection` has version `20211120.408` both in MELPA and Stable MELPA directories. Which matches the latest version of this package on MELPA - https://melpa.org/#/evil-collection.

**Comment by d12frosted** [comment]
Let me know if I can help you with this.
