### ISSUE TITLE
Upgrade auctex

### ISSUE THREAD

**Issue by mdbauer** [d12frosted/elpa-mirror#3]
Any chance you could update auctex? The new version 11.91 has some useful new features.

Your mirror is incredibly useful for folks like me behind coporate firewalls!

Thank you,
Michael

**Comment by d12frosted** [comment]
Hey @mdbauer 

Glad someone uses my mirror 😸 

You are talking about [GNU ELPA auctext package](https://elpa.gnu.org/packages/auctex.html), right?

It's strange because the last time my script updated anything in GNU folder was on 27/06/2017 14:21:11. And it seems that auctext was updated in on 25/07/2017. Seems like a bug! I'll investigate.

**Comment by d12frosted** [comment]
Fixed with https://github.com/d12frosted/elpa-mirror/commit/e9a7e5f21be7221330ca4dddf61f590325247bd6.

There is a problem with rsync, so I have switched to https for GNU until the issue is resolved. 

Anyways, thanks for reporting, without you I wouldn't notice the problem 😸

**Comment by d12frosted** [comment]
Fixed with https://github.com/d12frosted/elpa-mirror/commit/e9a7e5f21be7221330ca4dddf61f590325247bd6.

There is a problem with rsync, so I have switched to https for GNU until the issue is resolved. 

Anyways, thanks for reporting, without you I wouldn't notice the problem 😸

**Comment by d12frosted** [comment]
Fixed with https://github.com/d12frosted/elpa-mirror/commit/e9a7e5f21be7221330ca4dddf61f590325247bd6.

There is a problem with rsync, so I have switched to https for GNU until the issue is resolved. 

Anyways, thanks for reporting, without you I wouldn't notice the problem 😸

**Comment by d12frosted** [comment]
Sorry internet is being funky in my place 😨

**Comment by ninrod** [comment]
@d12frosted, I also use your mirror!

**Comment by d12frosted** [comment]
@ninrod haha, that's great to hear 😸
