### ISSUE TITLE
No updates in awhile

### ISSUE THREAD

**Issue by zlalanne** [d12frosted/elpa-mirror#5]
I noticed this mirror hasn't been getting updates since the end of July. Is it still being maintained?

**Comment by ninrod** [comment]
I think @d12frosted  is still around. I think it's just that we don't need to update that often using a setup like this. I also have a [personal](https://github.com/ninrod/rsynced-melpa) mirror, which I updated in june, 8th and still use it every day.

**Comment by d12frosted** [comment]
Hi everyone. Yeah, I am around :) It seems that something happened to the machine doing updates. I will check it once I have a chance to connect to it.

**Comment by d12frosted** [comment]
That's funny. The disk space has ended on that machine. Cleaned up a bit, so should be OK soon. Will close the issue once I see the update 😸 

Many thanks for noticing it. For some reason I rarely update. I'll think about adding some alerting here since you guys using this mirror ❤️ 💯

**Comment by d12frosted** [comment]
Nice, the Golem does his job now.

Also, I've set a simple notification system, so if it breaks again (for any reason) I'll get the notification.
